title: "Disabled Data Sovereignty"
description: "IVE Project supervised by Dr. KJ Hepworth"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

color_scheme: fun

just_the_docs:
  navigation:
    - title: Home
      url: /index

    - title: About
      url: /about

    - title: September
      url: /docs/sep/

    - title: October
      url: /docs/oct/

    - title: November
      url: /docs/nov/

    - title: December
      url: /docs/dec/

    - title: January
      url: /docs/jan/

    - title: February
      url: /docs/feb/

  footer_custom: footer_custom.html
